import { DEFAULT_CURRENCY } from "../constants/currency";
import type { Product } from "../types/product";
import cup2Img from "../assets/images/cup2.png";
import plateImg from "../assets/images/plate3.png";
import plate2Img from "../assets/images/plate4.png";
import sugarImg from "../assets/images/sugar.jpg";
import vase0Img from "../assets/images/vase4.jpg";
import kettleImg from "../assets/images/kettle3.jpg";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "ceramic-cup",
    name: "Ceramic Cup",
    description:
      "Minimalist ceramic cup with matte finish — perfect for coffee or tea.",
    price: 4500,
    currency: DEFAULT_CURRENCY,
    image: cup2Img,
    category: "cups-mugs",
  },
  {
    id: "2",
    slug: "handmade-plate",
    name: "Handmade Plate",
    description: "Elegant white ceramic plate with natural edges.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: plateImg,
    category: "plates-platters",
  },
  {
    id: "3",
    slug: "decorative-plate",
    name: "Decorative Plate",
    description:
      "A textured plate ideal for interior accents or serving desserts.",
    price: 3500,
    currency: DEFAULT_CURRENCY,
    image: plate2Img,
    category: "plates-platters",
  },
  {
    id: "4",
    slug: "sugar-bowl",
    name: "Sugar Bowl",
    description: "Compact sugar bowl with soft-glazed surface.",
    price: 1500,
    currency: DEFAULT_CURRENCY,
    image: sugarImg,
    category: "seasoning-containers",
  },
  {
    id: "5",
    slug: "modern-vase",
    name: "Modern Vase",
    description: "Matte ceramic vase with a sleek, modern design.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: vase0Img,
    category: "vases",
  },
  {
    id: "6",
    slug: "vintage-kettle",
    name: "Vintage Kettle",
    description: "Classic ceramic kettle with wooden handle and vintage look.",
    price: 6500,
    currency: DEFAULT_CURRENCY,
    image: kettleImg,
    category: "kettles",
  },
  {
    id: "7",
    slug: "ceramic-cup",
    name: "Ceramic Cup",
    description:
      "Minimalist ceramic cup with matte finish — perfect for coffee or tea.",
    price: 4500,
    currency: DEFAULT_CURRENCY,
    image: cup2Img,
    category: "cups-mugs",
  },
  {
    id: "8",
    slug: "handmade-plate",
    name: "Handmade Plate",
    description: "Elegant white ceramic plate with natural edges.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: plateImg,
    category: "plates-platters",
  },
  {
    id: "9",
    slug: "decorative-plate",
    name: "Decorative Plate",
    description:
      "A textured plate ideal for interior accents or serving desserts.",
    price: 3500,
    currency: DEFAULT_CURRENCY,
    image: plate2Img,
    category: "plates-platters",
  },
  {
    id: "10",
    slug: "sugar-bowl",
    name: "Sugar Bowl",
    description: "Compact sugar bowl with soft-glazed surface.",
    price: 1500,
    currency: DEFAULT_CURRENCY,
    image: sugarImg,
    category: "seasoning-containers",
  },
  {
    id: "11",
    slug: "modern-vase",
    name: "Modern Vase",
    description: "Matte ceramic vase with a sleek, modern design.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: vase0Img,
    category: "vases",
  },
  {
    id: "12",
    slug: "vintage-kettle",
    name: "Vintage Kettle",
    description: "Classic ceramic kettle with wooden handle and vintage look.",
    price: 6500,
    currency: DEFAULT_CURRENCY,
    image: kettleImg,
    category: "kettles",
  },
  {
    id: "13",
    slug: "ceramic-cup",
    name: "Ceramic Cup",
    description:
      "Minimalist ceramic cup with matte finish — perfect for coffee or tea.",
    price: 4500,
    currency: DEFAULT_CURRENCY,
    image: cup2Img,
    category: "cups-mugs",
  },
  {
    id: "14",
    slug: "handmade-plate",
    name: "Handmade Plate",
    description: "Elegant white ceramic plate with natural edges.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: plateImg,
    category: "plates-platters",
  },
  {
    id: "15",
    slug: "decorative-plate",
    name: "Decorative Plate",
    description:
      "A textured plate ideal for interior accents or serving desserts.",
    price: 3500,
    currency: DEFAULT_CURRENCY,
    image: plate2Img,
    category: "plates-platters",
  },
  {
    id: "16",
    slug: "sugar-bowl",
    name: "Sugar Bowl",
    description: "Compact sugar bowl with soft-glazed surface.",
    price: 1500,
    currency: DEFAULT_CURRENCY,
    image: sugarImg,
    category: "seasoning-containers",
  },
  {
    id: "17",
    slug: "modern-vase",
    name: "Modern Vase",
    description: "Matte ceramic vase with a sleek, modern design.",
    price: 2500,
    currency: DEFAULT_CURRENCY,
    image: vase0Img,
    category: "vases",
  },
  {
    id: "18",
    slug: "vintage-kettle",
    name: "Vintage Kettle",
    description: "Classic ceramic kettle with wooden handle and vintage look.",
    price: 6500,
    currency: DEFAULT_CURRENCY,
    image: kettleImg,
    category: "kettles",
  },
];
